import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/layout/Sidebar";
import AuthWrapper from "./authWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Grid layout */}
        <div className="flex min-h-screen">
          {/* Sidebar normal flow */}
          <Sidebar />

          {/* Main content */}
          <main className="flex-1 h-screen overflow-y-auto">
            <AuthWrapper>{children}</AuthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
